### PR TITLE
Force cloud type to match rrtmg input

### PR DESCRIPTION
**Pull request by SallyDa**

### CODE REVIEW

**Comment by lkluft** [comment]
I also thought about that after my issue yesterday.

Could we simply set the RRTMG input in the radiation class depending on the cloud class that is used?
_pseudo-code:_
```python
if isinstance(cloud, DirectInputCloud):
    rrtmg_input = 'direct_input_cloud'
```

**Comment by SallyDa** [comment]
Yes, we could also do something like that. I figured that we (or at least I) will still be playing around with the cloud classes / making new ones etc and then it is maybe easier to just add the extra property each time I design a new cloud class rather than having to change things in the core...

**Comment by SallyDa** [comment]
Ah, we could do a combination of both! So the rrtmg input is set based on a property specified in each cloud class. What do you think?

**Comment by lkluft** [comment]
> Ah, we could do a combination of both! So the rrtmg input is set based on a property specified in each cloud class. What do you think?

I like that approach! It should not be possible for the user (us) to use a cloud the wrong way. An attribute in the cloud class seems to be a perfect solution, as the RRTMG input should be constant for a given cloud class 👍

**Comment by SallyDa** [comment]
Okay, I'm just in the middle of implementing something else, but I'll do this as soon as I'm done :)

**Comment by SallyDa** [comment]
Update: I set the RRTMG input in the RRTMG class, not in the init, but when the first call is made to calculate radiative fluxes.

**Pull request merged**
