### PR TITLE
Remove basic logging configuration

### PR DESCRIPTION
**Pull request by lkluft**
I think we should remove the basic logging configuration. It should be up to the user to turn on and configure the ``logging`` module.
As a consequence we would need to set this in our run scripts. We could add a convenience function, though. What do you think?

### CODE REVIEW

**Comment by SallyDa** [comment]
This is what tells us what iteration we are at during the run, right? I am fine with including it in the run script instead, especially if you write a function for that!

**Comment by lkluft** [comment]
> This is what tells us what iteration we are at during the run, right?
Exactly! I think it is nice to keep the logging functionality in general, but it should not be enabled by default. (Back in the good old UNIX days a utility was supposed to be quiet, if everything is fine 😉 ).
I will simply hide the old logging configuration behind a function ``enable_logging()`` or something similar.

**Comment by SallyDa** [comment]
Sounds good :)

**Comment by lkluft** [comment]
Agreed! I modified the tutorials accordingly.

**Comment by SallyDa** [comment]
Thanks! I lost the data/tropical-standard.nc file somehow, also after I checked out your remove-log-config branch. Do you have it?

**Comment by SallyDa** [comment]
I'm having some problems with jupyter notebook, but I guess it should work now, thanks :)

**Pull request merged**
