### PR TITLE
Implement a flexible logging frequency

### PR DESCRIPTION
**Pull request by lkluft**

### CODE REVIEW

**Comment by lkluft** [comment]
The function `konrad.enable_logging()` enables logging in general (setting up the logger and the log level). The new keyword argument controls the frequency of the `Enter iteration X.` messages only

**Comment by SallyDa** [comment]
Yes I get that, but if you set up a logging frequency of whatever 10 days, but you haven't enabled logging, then you won't get any output, which might be a bit confusing, no?

**Comment by lkluft** [comment]
I see you point. But they are different mechanisms. One controls how many log messages are created, the other is a convenience function to print them on the console. You could also decide to not user `konrad.enable_logging` and setup your own logging that prints to a file or whatever.

But I could extend the docstring to mention, that one needs to enable logging in some way.

**Comment by SallyDa** [comment]
I doubt that someone would bother to set up their own logging, but okay, in theory :) Yes, I think it would be good to make it clear in the docstring.

**Pull request merged**
